title: <p align="center"> John Warner </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/john-j-warner/">LinkedIn</a> |
  <a href="https://github.com/jwarner3rd">GitHub</a>
  </p>
  
  <p align="justify">
  About me.
  <br><br>
  my focus.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
